/* 
EJERCICIOS SELECT 1
*/


/*  1. ESCRIBE UNA CONSULTA SQL PARA OBTENER TODOS LOS REGISTROS DE LA TABLA ACTORES  */

	SELECT * FROM actores;

/*  2. ESCRIBE UNA CONSULTA SQL QUE SELECCIONE LAS COLUMNAS TITULO Y TEMPORADA DE TODOS LOS EPISODIOS DISPONIBLES EN LA TABLA EPISODIOS */

	SELECT titulo, temporada FROM episodios;

/* 	3. ESCRIBE UNA CONSULTA SQL QUE SELECCIONE TODOS LOS AÑOS ÚNICOS DE LANZAIMENTO DE LAS SERIES DISPONIBLES */

	SELECT DISTINCT año_lanzamiento FROM series;
	
/*	4. ESCRIBE UNA CONSULTA SQL QUE SELECCIONE TODOS LOS AÑOS DE LANZAMIENTO ÚNICOS DE LA TABLA. LOS RESULTADOS DEBEN ESTAR ODENADOS DE FORMA DESCENDENTE. */

	SELECT DISTINCT año_lanzamiento FROM series ORDER BY año_lanzamiento DESC;

/*	5. ESCRIBE UNA CONSULTA SQL QUE SELECCIONE LOS NOMBRES Y LAS FECHAS DE NACIMIENTO DE TODOS LOS ACTORES. ORDENA LOS RESULTADOS DE MANERA DESCENDENTE POR LA FECHA DE NACIMIENTO */

	SELECT nombre, fecha_nacimiento FROM actores ORDER BY fecha_nacimiento DESC;

/*	6. ESCRIBE UNA CONSULTA SQL QUE SELECCIONE LOS 5 PRIMEROS NOMBRE EN ORDEN ALFABETICO*/

	SELECT nombre FROM actores ORDER BY nombre LIMIT 5;

/* 	7. ESCRIBE UNA CONSULTA SQL QUE SELECCIONE TODOS LOS REGISTROS DE LAS SERIES CUY0 GÉNERO ES COMEDIA*/
	
    SELECT * FROM series WHERE genero = 'comedia';

/*  8. ESCRIBE UNA CONSULTA SQL QUE SELECCIONE EL TÍTULO Y AÑO DE LANZAMIENTO DE LAS SERIES CUYO AÑO DE LANZAMIENTO SEA MAYOR DE 2020 */

	SELECT titulo, año_lanzamiento FROM series WHERE año_lanzamiento > 2020;

/* 9. ESCRIBE UNA CONSULTA SQL QUE SELECCIONE TODAS LAS COLUMNAS DE TODAS LAS SERIES DONDE EL GÉNERO SEA DRAMA O CIENCIA FiCCIÓN */

	SELECT * FROM series WHERE genero = 'drama' OR genero = 'ciencia ficcion';

/* 10. ESCRIBE UNA CONSULTA SQL QUE SELECCIONE LAS SERIES DEL GÉNERO DRAMA O QUE SE HAYAN LANZADO EN EL AÑO 2020 */

	SELECT * FROM series WHERE genero = 'drama' OR año_lanzamiento = 2020;

/* 11. ESCRIBE UNA CONSULTA SQL QUE SELECCIONE TODOS LOS EPISODIOS ORDENADOS POR TEMPORADA (ASCENDENTE) Y LUEGO POR RATING DE IMDB (DESDCENDENTE) */

	SELECT * FROM episodios ORDER BY temporada, rating_imdb desc;

/* 12. ESCRIBE UNA CONSULTA SQL QUE SELECCIONE LOS TITULOS Y DURACIONES DE LOS EPISODIOS CON RATING SUPERIOR A 7,5 ORDENADOS POR DURACION DESCENDENTE, LIMITANDO EL RESULTADO A 10 REGISTROS */

	SELECT titulo, duracion, rating_imdb FROM episodios WHERE rating_imdb > 7.5 ORDER BY duracion DESC LIMIT 10;

/* 13. ESCRIBE UNA CONSULTA SQL QUE SELECCIONE LAS SERIES DEL GÉNERO DRAMA O TRHILLER Y QUE SE HAYAN LANZADO DESPUÉS DEL 2015 */

	SELECT * FROM series WHERE (genero = 'drama' OR genero = 'thriller') AND año_lanzamiento > 2015;

/* 14. ESCRIBE UNA CONSULTA SQL QUE SELECCIONE LAS SERIES QUE NO SEAN DE GÉNERO COMEDIA Y QUE NO SE HAYAN LANZADO EN LOS AÑOS 2015, 2016 0 2017*/
	
   SELECT titulo, genero, año_lanzamiento 
FROM Series 
WHERE genero != 'Comedia' 
  AND (año_lanzamiento < 2015 OR año_lanzamiento > 2017);