/*	1. ESCRIBE UNA CONSULTA SQL QUE SELECCIONE TODAS LAS COLUMNAS DE TODAS LAS SERIES EXCLUYENDO AQUELLAS CUYO GÉNERO SEA DRAMA O BIOGRAFÍA  */

SELECT * FROM series WHERE genero NOT IN ('DRAMA', 'BIOGRAFÍA');

/*	2.  ESCRIBE UNA CONSULTA SQL QUE SELECCIONE TODAS LA INFORMACIÓN DE LAS SERIES QUE CONTENGAN LA PALABRA LUCHA EN SU DESCRIPCIÓN */

SELECT * FROM series WHERE descripcion LIKE '%lucha%';

/*	3.  ESCRIBE UNA CONSULTA SQL QUE SELECCIONE TODOS LOS ACTORES QUE HAYAN NACIDO ANTES DE 1970 O DESPUES DE 1995 */

SELECT * FROM actores WHERE fecha_nacimiento < '1970-01-01' OR fecha_nacimiento > '1995-12-31';

/*	4.  ESCRIBE UNA CONSULTA SQL QUE SELECCIONE TODOS LOS EPISODIOS EXCEPTO LOS QUE DUREN MENOS DE 45 MINUTOS Y SEAN DE LA TEMPORADA 1 */

SELECT * FROM episodios WHERE duracion > 45 AND temporada = 1;

/*	5.  ESCRIBE UNA CONSULTA SQL QUE SELECCIONE TODOS LOS ACTORES EXCEPTO AQUELLOS QUE SE LLAMEN "BRYAN CRANSTON", "STEVE CARELL" O "HENRY CAVILL" */

SELECT * FROM actores WHERE nombre NOT IN('bryan Cranston', 'steve carell', 'henry cavill');

/*	6.  ESCRIBE UNA CONSULTA SQL QUE SELECCIONE TODOS LOS EPISODIOS CUYO TÍTULO TERMINE CON "DAY" */

SELECT * FROM episodios WHERE titulo LIKE '%DAY';

/*	7.  ESCRIBE UNA CONSULTA SQL QUE SELECCIONE TODOS LOS SERIES CUYO TÍTULO NO EMPIECE CON "THE" */

SELECT * FROM series WHERE titulo NOT LIKE 'THE%';

/*	8.  ESCRIBE UNA CONSULTA SQL QUE SELECCIONE LAS SERIES CUYO TÍTULO CONTENGA EXACTAMENTE 11 CARACTERES DESPUÉS DE "THE" */

SELECT * FROM series WHERE titulo LIKE 'THE ___________';

/*	9.	MUESTRA LAS SERIES DEL GÉNERO "DRAMA" O "CIENCIA FICCION" LANZADAS ENTRE 2010 Y 2020 ORDENADAS POR AÑO DE FORMA DESCENDENTE */

SELECT genero, titulo, año_lanzamiento 
FROM series 
WHERE genero 
IN('drama','ciencia ficcion') AND (año_lanzamiento >= 2010 AND año_lanzamiento <= 2020) ORDER BY año_lanzamiento DESC;

/*	10.	MUESTRA LAS 3 SERIES MÁS RECIENTES CUYOS TÍTULOS EMPIECEN CON "B" O "S" */



/*	11.	MUESTRA TODOS LOS EPISODIOS CUYO TÍTULO EMPIECE CON VOCAL Y TENGAN UN RATING DE 0 O SUPERIOR */

/*	12. MUESTRA TODOS LOS EPISODIOS QUE CONTENGA "THE" EN EL TÍTULO, DUREN MÁS DE 40 MINUTOS, SEAN DE LA TEMPORADA 1 0 2 Y TENGAN UN RATING MAYOR A 8,5 */

/*	13.	CREA UNA CONSULTA QUE MUESTRE :
	- TITULO Y DURACIÓN DE EPISODIOS
    - QUE NO SEAN DE LA TEMPORADA 1
    - QUE DUREN ENTRE 45 Y 60 MINUTOS
    - QUE TENGAN UN RATING ENTRE 8,5 Y 9,5
    - QUE SU TÍTULO CONTENGA "THE" O TERMINE EN "S"
    - OREDENADOS POR RATING DE FORMA DESCENDENTE
    - LIMITADO A LOS 10 PRIMEROS RESULTADOS
 */
